"""Golden-vector acceptance tests for the rewritten envelope.py.

These tests pin envelope.py's output byte-for-byte against the rover's LOCKED
v0.1.0 wire contract (friday-labs-os branch boundary/command-center-contract,
commit 10fa3f0).  The seed, payloads, and expected hex strings were generated by
running the rover's real protocol.py and independently verified.  Any change that
shifts a byte in _signing_bytes, the signature, or the wire encoding is a
contract break and must not land.
"""

from __future__ import annotations

import pytest

import envelope as env

# ---------------------------------------------------------------------------
# Golden-vector fixture data (do not modify — these are ground truth)
# ---------------------------------------------------------------------------

SEED_HEX = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
PUB_HEX  = "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"

# Command vector
CMD_ROVER_ID   = "MARK1-001"
CMD_SENDER_ID  = "OP-001"
CMD_MSG_ID     = 1
CMD_NONCE      = 1
CMD_ISSUED_AT  = 1751328000000
CMD_EXPIRES_AT = 1751328030000
CMD_PAYLOAD_HEX = (
    "a365636c617373666d6f74696f6e6f6c696e6561725f76656c6f63697479fb"
    "3fe000000000000070616e67756c61725f76656c6f63697479fb0000000000000000"
)
CMD_SIGNING_BYTES_HEX = (
    "a8656e6f6e636501666d73675f696401677061796c6f61645841"
    "a365636c617373666d6f74696f6e6f6c696e6561725f76656c6f63697479fb"
    "3fe000000000000070616e67756c61725f76656c6f63697479fb0000000000000000"
    "68726f7665725f6964694d41524b312d303031696973737565645f61741b"
    "00000197c34888006973656e6465725f6964664f502d3030316a657870697265735f"
    "61741b00000197c348fd307070726f746f636f6c5f76657273696f6ea3656d616a6f"
    "7200656d696e6f720165706174636800"
)
CMD_SIGNATURE_HEX = (
    "f3c7ec2fe3bf8fc1f39a5e0ad5e1762d34342a9af38469bd72b85c92c1a4ca5"
    "bdac242cf8d15b85b527ee48b2d9ede73bd9bdf1f88b6fdbc381356b309833d04"
)
CMD_WIRE_HEX = (
    "a97070726f746f636f6c5f76657273696f6ea3656d616a6f7200656d696e6f72"
    "016570617463680068726f7665725f6964694d41524b312d3030316973656e6465"
    "725f6964664f502d303031666d73675f696401656e6f6e636501696973737565645f"
    "61741b00000197c34888006a657870697265735f61741b00000197c348fd30677061"
    "796c6f61645841a365636c617373666d6f74696f6e6f6c696e6561725f76656c6f63"
    "697479fb3fe000000000000070616e67756c61725f76656c6f63697479fb00000000"
    "00000000697369676e61747572655840f3c7ec2fe3bf8fc1f39a5e0ad5e1762d3434"
    "2a9af38469bd72b85c92c1a4ca5bdac242cf8d15b85b527ee48b2d9ede73bd9bdf1f"
    "88b6fdbc381356b309833d04"
)

# Telemetry vector
TLM_ROVER_ID   = "MARK1-001"
TLM_MSG_ID     = 100
TLM_NONCE      = 1
TLM_ISSUED_AT  = 1751328000000
TLM_EXPIRES_AT = 1751328030000
TLM_PAYLOAD_HEX = (
    "a36178fb3ff80000000000006179fb0000000000000000"
    "657468657461fb0000000000000000"
)
TLM_SIGNING_BYTES_HEX = (
    "a8656e6f6e636501666d73675f69641864677061796c6f61645826"
    "a36178fb3ff80000000000006179fb0000000000000000657468657461fb"
    "000000000000000068726f7665725f6964694d41524b312d303031696973737565"
    "645f61741b00000197c34888006973656e6465725f6964694d41524b312d303031"
    "6a657870697265735f61741b00000197c348fd307070726f746f636f6c5f766572"
    "73696f6ea3656d616a6f7200656d696e6f720165706174636800"
)
TLM_SIGNATURE_HEX = (
    "d9be70640790f37e4a92739891021c582b80670cbc91a708d7b23510c5cec0e"
    "e3e148d931fc489d6a935b2cfe32a078a9896758a429c13714acab2788e84a004"
)
TLM_WIRE_HEX = (
    "a97070726f746f636f6c5f76657273696f6ea3656d616a6f7200656d696e6f7201657061"
    "7463680068726f7665725f6964694d41524b312d3030316973656e6465725f6964694d41"
    "524b312d303031666d73675f69641864656e6f6e636501696973737565645f61741b0000"
    "0197c34888006a657870697265735f61741b00000197c348fd30677061796c6f61645826"
    "a36178fb3ff80000000000006179fb0000000000000000657468657461fb000000000000"
    "0000697369676e61747572655840d9be70640790f37e4a92739891021c582b80670cbc91"
    "a708d7b23510c5cec0ee3e148d931fc489d6a935b2cfe32a078a9896758a429c13714aca"
    "b2788e84a004"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _private_key():
    return env.private_key_from_hex(SEED_HEX)


def _public_key():
    return env.public_key_from_hex(PUB_HEX)

# ---------------------------------------------------------------------------
# Command vector tests
# ---------------------------------------------------------------------------

def test_command_signing_bytes_hex():
    """_signing_bytes must produce the exact canonical CBOR the rover signs over."""
    payload = bytes.fromhex(CMD_PAYLOAD_HEX)
    e = env.build_envelope(
        rover_id=CMD_ROVER_ID,
        sender_id=CMD_SENDER_ID,
        msg_id=CMD_MSG_ID,
        nonce=CMD_NONCE,
        issued_at=CMD_ISSUED_AT,
        expires_at=CMD_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert env._signing_bytes(e).hex() == CMD_SIGNING_BYTES_HEX


def test_command_signature_hex():
    """Ed25519 signature over the command envelope must match the golden vector."""
    payload = bytes.fromhex(CMD_PAYLOAD_HEX)
    e = env.build_envelope(
        rover_id=CMD_ROVER_ID,
        sender_id=CMD_SENDER_ID,
        msg_id=CMD_MSG_ID,
        nonce=CMD_NONCE,
        issued_at=CMD_ISSUED_AT,
        expires_at=CMD_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert e["signature"].hex() == CMD_SIGNATURE_HEX


def test_command_wire_hex():
    """Wire encoding (cbor2.dumps) of the command envelope must be byte-exact."""
    payload = bytes.fromhex(CMD_PAYLOAD_HEX)
    e = env.build_envelope(
        rover_id=CMD_ROVER_ID,
        sender_id=CMD_SENDER_ID,
        msg_id=CMD_MSG_ID,
        nonce=CMD_NONCE,
        issued_at=CMD_ISSUED_AT,
        expires_at=CMD_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert env.encode(e).hex() == CMD_WIRE_HEX


def test_command_verify():
    """verify() must return True for the golden command envelope."""
    payload = bytes.fromhex(CMD_PAYLOAD_HEX)
    e = env.build_envelope(
        rover_id=CMD_ROVER_ID,
        sender_id=CMD_SENDER_ID,
        msg_id=CMD_MSG_ID,
        nonce=CMD_NONCE,
        issued_at=CMD_ISSUED_AT,
        expires_at=CMD_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert env.verify(e, _public_key()) is True


def test_command_roundtrip_decode_encode():
    """decode(encode(e)) must reproduce the original envelope and still verify."""
    payload = bytes.fromhex(CMD_PAYLOAD_HEX)
    e = env.build_envelope(
        rover_id=CMD_ROVER_ID,
        sender_id=CMD_SENDER_ID,
        msg_id=CMD_MSG_ID,
        nonce=CMD_NONCE,
        issued_at=CMD_ISSUED_AT,
        expires_at=CMD_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    wire = env.encode(e)
    decoded = env.decode(wire)
    assert decoded["rover_id"] == CMD_ROVER_ID
    assert decoded["sender_id"] == CMD_SENDER_ID
    assert decoded["msg_id"] == CMD_MSG_ID
    assert decoded["nonce"] == CMD_NONCE
    assert decoded["issued_at"] == CMD_ISSUED_AT
    assert decoded["expires_at"] == CMD_EXPIRES_AT
    assert decoded["payload"] == payload
    assert env.verify(decoded, _public_key()) is True

# ---------------------------------------------------------------------------
# Telemetry vector tests
# ---------------------------------------------------------------------------

def test_telemetry_signing_bytes_hex():
    """_signing_bytes must produce the exact canonical CBOR for the telemetry vector."""
    payload = bytes.fromhex(TLM_PAYLOAD_HEX)
    e = env.sign_telemetry(
        rover_id=TLM_ROVER_ID,
        msg_id=TLM_MSG_ID,
        nonce=TLM_NONCE,
        issued_at=TLM_ISSUED_AT,
        expires_at=TLM_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert env._signing_bytes(e).hex() == TLM_SIGNING_BYTES_HEX


def test_telemetry_signature_hex():
    """Ed25519 signature over the telemetry envelope must match the golden vector."""
    payload = bytes.fromhex(TLM_PAYLOAD_HEX)
    e = env.sign_telemetry(
        rover_id=TLM_ROVER_ID,
        msg_id=TLM_MSG_ID,
        nonce=TLM_NONCE,
        issued_at=TLM_ISSUED_AT,
        expires_at=TLM_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert e["signature"].hex() == TLM_SIGNATURE_HEX


def test_telemetry_wire_hex():
    """Wire encoding of the telemetry envelope must be byte-exact."""
    payload = bytes.fromhex(TLM_PAYLOAD_HEX)
    e = env.sign_telemetry(
        rover_id=TLM_ROVER_ID,
        msg_id=TLM_MSG_ID,
        nonce=TLM_NONCE,
        issued_at=TLM_ISSUED_AT,
        expires_at=TLM_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert env.encode(e).hex() == TLM_WIRE_HEX


def test_telemetry_sender_id_equals_rover_id():
    """sign_telemetry must set sender_id == rover_id (unified envelope shape)."""
    payload = bytes.fromhex(TLM_PAYLOAD_HEX)
    e = env.sign_telemetry(
        rover_id=TLM_ROVER_ID,
        msg_id=TLM_MSG_ID,
        nonce=TLM_NONCE,
        issued_at=TLM_ISSUED_AT,
        expires_at=TLM_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert e["sender_id"] == TLM_ROVER_ID


def test_telemetry_verify():
    """verify() must return True for the golden telemetry envelope."""
    payload = bytes.fromhex(TLM_PAYLOAD_HEX)
    e = env.sign_telemetry(
        rover_id=TLM_ROVER_ID,
        msg_id=TLM_MSG_ID,
        nonce=TLM_NONCE,
        issued_at=TLM_ISSUED_AT,
        expires_at=TLM_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    assert env.verify(e, _public_key()) is True


def test_telemetry_roundtrip_decode_encode():
    """decode(encode(e)) must reproduce the telemetry envelope and still verify."""
    payload = bytes.fromhex(TLM_PAYLOAD_HEX)
    e = env.sign_telemetry(
        rover_id=TLM_ROVER_ID,
        msg_id=TLM_MSG_ID,
        nonce=TLM_NONCE,
        issued_at=TLM_ISSUED_AT,
        expires_at=TLM_EXPIRES_AT,
        payload=payload,
        private_key=_private_key(),
    )
    wire = env.encode(e)
    decoded = env.decode(wire)
    assert decoded["rover_id"] == TLM_ROVER_ID
    assert decoded["sender_id"] == TLM_ROVER_ID
    assert decoded["msg_id"] == TLM_MSG_ID
    assert decoded["nonce"] == TLM_NONCE
    assert decoded["issued_at"] == TLM_ISSUED_AT
    assert decoded["expires_at"] == TLM_EXPIRES_AT
    assert decoded["payload"] == payload
    assert env.verify(decoded, _public_key()) is True

# ---------------------------------------------------------------------------
# Type-enforcement regression tests (change #2)
# ---------------------------------------------------------------------------

def test_build_envelope_dict_payload_raises_type_error():
    """Passing a raw dict as payload must raise TypeError — it must be pre-serialized bytes."""
    priv = _private_key()
    with pytest.raises(TypeError):
        env.build_envelope(
            rover_id="MARK1-001",
            sender_id="OP-001",
            msg_id=1,
            nonce=1,
            issued_at=CMD_ISSUED_AT,
            expires_at=CMD_EXPIRES_AT,
            payload={"class": "motion"},  # dict — must be rejected
            private_key=priv,
        )


def test_build_envelope_float_issued_at_raises_type_error():
    """Passing a float for issued_at must raise TypeError — must be int epoch-ms."""
    priv = _private_key()
    with pytest.raises(TypeError):
        env.build_envelope(
            rover_id="MARK1-001",
            sender_id="OP-001",
            msg_id=1,
            nonce=1,
            issued_at=1751328000.0,   # float seconds — must be rejected
            expires_at=CMD_EXPIRES_AT,
            payload=bytes.fromhex(CMD_PAYLOAD_HEX),
            private_key=priv,
        )


def test_build_envelope_float_expires_at_raises_type_error():
    """Passing a float for expires_at must raise TypeError — must be int epoch-ms."""
    priv = _private_key()
    with pytest.raises(TypeError):
        env.build_envelope(
            rover_id="MARK1-001",
            sender_id="OP-001",
            msg_id=1,
            nonce=1,
            issued_at=CMD_ISSUED_AT,
            expires_at=1751328030.0,  # float seconds — must be rejected
            payload=bytes.fromhex(CMD_PAYLOAD_HEX),
            private_key=priv,
        )


def test_build_envelope_bytearray_payload_accepted():
    """bytearray (a mutable bytes view) must be accepted as payload, not rejected."""
    priv = _private_key()
    payload = bytearray(bytes.fromhex(CMD_PAYLOAD_HEX))
    # Should not raise
    e = env.build_envelope(
        rover_id="MARK1-001",
        sender_id="OP-001",
        msg_id=1,
        nonce=1,
        issued_at=CMD_ISSUED_AT,
        expires_at=CMD_EXPIRES_AT,
        payload=payload,
        private_key=priv,
    )
    assert "signature" in e

# ---------------------------------------------------------------------------
# Constants (change #3)
# ---------------------------------------------------------------------------

def test_time_constants_are_milliseconds():
    """DEFAULT_EXPIRY_MS must be 30_000 (int ms) and SKEW_MS must be 5_000."""
    assert env.DEFAULT_EXPIRY_MS == 30_000
    assert env.SKEW_MS == 5_000
    # The old float-seconds constant must no longer exist
    assert not hasattr(env, "DEFAULT_EXPIRY_S"), (
        "DEFAULT_EXPIRY_S was removed; callers must use DEFAULT_EXPIRY_MS"
    )
